[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Regular Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[cursor]
style = {shape = "Beam", blinking = "Always"}
thickness = 0.2